language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
branches:
  only:
    - master
os:
  - linux
  - mac
  - windows
script:
  - rustup target add thumbv7em-none-eabihf
  - cargo build --release
